### ISSUE TITLE
Serverless-bundle now officially supported as one of our boilerplates

### ISSUE THREAD

**Issue by Vadorequest** [AnomalyInnovations/serverless-bundle#10]
FYI, we have just released a boilerplate featuring `serverless-bundle` at https://github.com/UnlyEd/boilerplates-generator/tree/master/templates/node-v10.x-aws-serverless-with-serverless-bundle

It contains everything for a quick getting started with serverless and serverless-bundle! :)

**Comment by jayair** [comment]
Awesome! Thank you!
