### ISSUE TITLE
Aliases not working on jest

### ISSUE THREAD

**Issue by bashdosage** [AnomalyInnovations/serverless-bundle#104]
Hi, first of all, I wanted to say what a great job you are doing with this project. It really has made life easier.

I created an alias for a lib directory, and it works fine using serverless invoke, and deploy. When I try to run npm test it cannot find the module. Is this by design? Or could I be missing something?

I added the following to serverless.yml:
custom:
   bundle:
      aliases:
         - "lib": "../../lib"

Thanks!

**Comment by jayair** [comment]
Yeah you are right. We don't apply it for the tests. Would somebody like to help with this?

**Comment by chanthafef** [comment]
Hi. I can give it a try.

We need to use what jest calls [moduleNameMapper](https://jestjs.io/docs/en/configuration#modulenamemapper-objectstring-string--arraystring).

# option 1 
- In ``scripts/config/paths`` we add a path to a ``appServerlessYamlFile: resolveApp('serverless.yml')``.
- in ``createJestConfig.js`` we use something like [js-yaml](https://www.npmjs.com/package/js-yaml) to get the aliases from ``appServerlessYamlFile``.
- we transform each alias to [regex](https://jestjs.io/docs/en/configuration#modulenamemapper-objectstring-string--arraystring)
- add them to the jest config under ``moduleNameMapper``.

# option 2
- add ``moduleNameMapper`` to the list of ``supportedKeys`` in ``createJestConfig.js``
- update ``README`` to inform users they have to add their aliases in the package.json file

Like this :
```
"jest": {
    "moduleNameMapper": {
      "libs(.*)$": "<rootDir>/libs/$1"
    }
  }
```

**Comment by chanthafef** [comment]
PR for option 2:
https://github.com/AnomalyInnovations/serverless-bundle/pull/115

**Comment by jayair** [comment]
Thanks for the PR. Published a new release: https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.9.1.

Update using:

``` bash
$ npm install --save-dev --save-exact serverless-bundle@1.9.1
```
