### ISSUE TITLE
How to add other babbel plugins?

### ISSUE THREAD

**Issue by namelesswc** [AnomalyInnovations/serverless-bundle#107]
When using this package I have no configuration files like the .babelrc file.
How can I add other plugins to babel (babel-plugin-rewire)?

**Comment by jayair** [comment]
Yeah we don't have a way to do that. We have added ways to customize the some Webpack options but not Babel.

**Comment by namelesswc** [comment]
Alright. Guess it's time to finally time for me to setup all the plugins myself instead of using the bundle.

**Comment by JoaquinFernandez** [comment]
> Yeah we don't have a way to do that. We have added ways to customize the some Webpack options but not Babel.

Same issue here, I use babel-plugin-rewire for exposing non exported functions and be able to unit test them. Per the docs and your answer, there is no way to do that via babel config, do you have any alternatives?

**Comment by jayair** [comment]
It's tricky to do that here. But if you open a new issue for this specific plugin and if many other folks need it, we'll look at adding it.

**Comment by lepirlouit** [comment]
I'll also be interested in that plugin to be added
is there an issue that was open for this specific plugin ?
