### ISSUE TITLE
Babel Issue with Private Class Fields handling 

### ISSUE THREAD

**Issue by larrybek** [AnomalyInnovations/serverless-bundle#13]
Babel is not handling Node 10 Private Class Fields. Using # as private field is giving error as `Unexpected character '#';`
As you have pointed just add babel configurations to support it.
Will be happy to hear from you soon.

Also other issues with submitting class properties is not supported in it providing this error:
`Support for the experimental syntax 'classProperties' isn't currently enabled`

**Comment by jayair** [comment]
Oh interesting, can you post some sample code that I can reproduce this and test it with? We'll be upgrading to Node 10 soon, so this'll be useful.

**Comment by larrybek** [comment]
@jayair you can just use a simple code of this to replicate the issue I got:
`class testClass { 
    #attribute1;
    #attribute2;
   constructor(data) {
     this.#attribute1 =  data.attribute1
   }
}`

or even without # second issue
`class testClass { 
    attribute1;
    attribute2;
   constructor(data) {
     this.attribute1 =  data.attribute1
   }
}`
`Support for the experimental syntax 'classProperties' isn't currently enabled`

**Comment by jayair** [comment]
Thanks.

Added - https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.2.4.
