### ISSUE TITLE
20 errors and 0 warnings potentially fixable with the `--fix` option.

### ISSUE THREAD

**Issue by OmarKhattab** [AnomalyInnovations/serverless-bundle#14]
I get some linting errors when I invoke function locally. How can I fix these errors?

**Comment by jayair** [comment]
It depends on the errors you are getting. It's usually a good idea to fix these errors. But you could optionally disable linting all together by setting `linting: false` - https://github.com/AnomalyInnovations/serverless-bundle#options.
