### ISSUE TITLE
Serverless plugin "serverless-bundle" not found. CICD Deployment.

### ISSUE THREAD

**Issue by lionheart2013** [AnomalyInnovations/serverless-bundle#144]
I have a multiple serverless.yml from different directories. I want to reference serverless-bundle on one of my serverless.yml. The serverless-bundle was installed on project root. But failed I tried the following - ../../node_modules/serverless-bundle and just - serverless-bundle but got the same error, "Serverless plugin "serverless-bundle" not found". Please let me know.
NOTE: I am deploying using Serverless CICD

**Comment by jayair** [comment]
We support this setup — https://github.com/AnomalyInnovations/serverless-bundle#nested-services

Is that what you are doing?

**Comment by lionheart2013** [comment]
> We support this setup — https://github.com/AnomalyInnovations/serverless-bundle#nested-services
> 
> Is that what you are doing?

@jayair, yes thats exactly what I am trying to do, problem is, its not working I am getting the error "serverless-bundle" not found. To make this work I used npm preinstall script to navigate back and then install "serverless-bundle", not sure if this is the right approach. But just relying on this package alone and expect everything will work, clearly its not. Let me know if I missed something here. Thank you

**Comment by jayair** [comment]
Can you share a sample repo? Because the setup listed in the README works as-is.

**Comment by lionheart2013** [comment]
> Can you share a sample repo? Because the setup listed in the README works as-is.

Sharing you my sample repo https://github.com/lionheart2013/nested-services, also please note that setup listed on README works only on local machine, but failed on Serverless Framework CICD. As I said on my previous comment to make this works I added an npm preinstall script on nested service(service1) eg. "preinstall":"cd ../ && npm i serverless-bundle". 

<img width="936" alt="Screen Shot 2020-11-16 at 7 31 41 AM" src="https://user-images.githubusercontent.com/5111948/99199994-c87fb380-27dd-11eb-97a4-4c277952a56d.png">

**Comment by jayair** [comment]
Ah this is more an issue with their service. They aren't doing a root npm install. We support this natively on [Seed](www.seed.run).

**Comment by lionheart2013** [comment]
> Ah this is more an issue with their service. They aren't doing a root npm install. We support this natively on [Seed](www.seed.run).

gotcha, thanks for clarification.
