### ISSUE TITLE
Using other testrunners

### ISSUE THREAD

**Issue by tume** [AnomalyInnovations/serverless-bundle#15]
I have been trying to use ava with this project and got stuck pretty fast :). After figuring out all those babel configs for compiling my source code the problem now seems to be that I'm including files outside my working directory (lib is located outside my services directory). 

It seems that your babel-jest integration works fine though. Wondering whether it would be beneficial to maybe post some guide on how to use others or which things to consider when trying?

(Pretty newbie what comes to babel/webpack so my conclucions might be a bit wrong also)

**Comment by jayair** [comment]
Yeah the issue here is that the other test runners would need to run the babel configs as well. It's a little tricky to do and I'm not too familiar with Ava. If you figure out how to get it to work then we can definitely post a guide.

**Comment by jayair** [comment]
Closing this for now.
