### ISSUE TITLE
compiling code with react

### ISSUE THREAD

**Issue by DnSu** [AnomalyInnovations/serverless-bundle#152]
when I included react syntax, I get

Support for the experimental syntax 'jsx' isn't currently enabled

is there a work around for this, I'm trying to write a sitemap generator in lambda via the react-router-sitemap package

**Comment by jayair** [comment]
I don't think we are doing handling JSX currently. We'll need to add a loader for it. Feel free to open a PR.

**Comment by PenguinOfWar** [comment]
Support for JSX and TSX is contained in #168
