### ISSUE TITLE
Use esbuild instead of webpack

### ISSUE THREAD

**Issue by thomaschaaf** [AnomalyInnovations/serverless-bundle#153]
I came across: https://github.com/floydspace/serverless-esbuild do you think it would make sense to use this instead of webpack?

**Comment by jayair** [comment]
I haven't played around with esbuild but it does look really promising! It's not trivial to port bundle over to use that plugin however.

But I'd like to keep an eye on this, slow builds are a huge pain point.

**Comment by JoaquinFernandez** [comment]
Hi!
It looks like serverless moved to esbuild recently:

https://github.com/serverless/serverless/pull/9962

Maybe it's a good opportunity to make the change?

**Comment by jayair** [comment]
We added support for this recently: https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v5.0.0

Let me close this to avoid confusion.
