### ISSUE TITLE
Error on CI/CD deployment: Error: npm ls -prod -json -depth=1 failed with code 7

### ISSUE THREAD

**Issue by kristianjabilles-ms** [AnomalyInnovations/serverless-bundle#164]
Hi All, I am having some issues when the app is deployed with CI/CD, although `sls deploy` works fine locally.

Here is the log:

```
Serverless: Bundling with Webpack...
Serverless: Invoke webpack:package
 
  Error --------------------------------------------------
 
  Error: npm ls -prod -json -depth=1 failed with code 7
      at ChildProcess.<anonymous> (/drone/src/github.com/github-account/my-app/node_modules/serverless-webpack/lib/utils.js:91:16)
      at ChildProcess.emit (events.js:223:5)
      at ChildProcess.EventEmitter.emit (domain.js:475:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:430:11)
      at Socket.emit (events.js:223:5)
      at Socket.EventEmitter.emit (domain.js:475:20)
      at Pipe.<anonymous> (net.js:664:12)
```

```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.14.1
     Framework Version:         2.11.1 (local)
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.3.0
```

serverless-bundle: `4.0.1`

Did anyone encounter this issue before?

**Comment by mellson** [comment]
@kristianjabilles-ms did you figure out the cause for this problem?

**Comment by mellson** [comment]
I figured it out. I had to set [my packager](https://github.com/AnomalyInnovations/serverless-bundle#options) to `yarn` because I'm using yarn workspaces.

**Comment by spock-yh** [comment]
I'm having the same problem, but I'm not using yarn workspaces. My projects uses lerna and npm, so I assume I shouldn't change my packager to yarn. But I'm getting the same error, only when running in jenkins (everything works perfectly locally). Any idea what is causing this?

**Comment by spock-yh** [comment]
> I'm having the same problem, but I'm not using yarn workspaces. My projects uses lerna and npm, so I assume I shouldn't change my packager to yarn. But I'm getting the same error, only when running in jenkins (everything works perfectly locally). Any idea what is causing this?

For anyone with the same problem, in my case the issue was an authentication problem with our NPM repository (it was set up properly locally, but not in the CI server for this specific stage of the pipeline).
