### ISSUE TITLE
ERROR in NormalModuleFactory.beforeResolve

### ISSUE THREAD

**Issue by ayushsharma82** [AnomalyInnovations/serverless-bundle#166]
serverless-bundle version: ^4.1.0

Getting this error with `serverless package` command:

```
Serverless: Bundling with Webpack...
ERROR in NormalModuleFactory.beforeResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it 
instead. Returning false will ignore the request and results in no module created.

webpack compiled with 1 error
```

**Comment by ayushsharma82** [comment]
My Bad. I had webpack v5 installed along with this plugin in `node_modules`. 

Uninstalling that webpack package fixed this error.

**Comment by nbeny** [comment]
It can also be because you don't have serverless-bundle installed...
