### ISSUE TITLE
serverless-bundle is not compatible with serverless-webpack

### ISSUE THREAD

**Issue by robsonkades** [AnomalyInnovations/serverless-bundle#172]
serverless-webpack config detected in serverless.yml. serverless-bundle is not compatible with serverless-webpack
```
    "serverless-bundle": "^4.1.0",
    "serverless-offline": "^6.8.0",
    "serverless-webpack": "^5.3.5"
```

**Comment by PenguinOfWar** [comment]
What is your use case? Internally, this library already uses `serverless-webpack` and doesn't support many external hooks to change that due to its PNP nature.

**Comment by robsonkades** [comment]
I am closing because this is no longer necessary
