### ISSUE TITLE
Building casbin with serverless-bundle

### ISSUE THREAD

**Issue by mkherlakian** [AnomalyInnovations/serverless-bundle#174]
I'm trying to include casbin, a popular authorization library (https://www.npmjs.com/package/casbin), in my serverless app using serverless-bundle.
I've tracked it down to the fact that casbin publishes 2 versions of their module - esm and cjs under the lib directory in node_modules.
The webpack's loader included in serverless-bundle insists on loading the esm version, and that results in a compile error:

```

> ERROR in <...>/node_modules/casbin/lib/esm/model/model.js 139:38
> Module parse failed: Unexpected token (139:38)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |     async buildIncrementalRoleLinks(rm, op, sec, ptype, rules) {
> |         if (sec === 'g') {
> >             await this.model.get(sec)?.get(ptype)?.buildIncrementalRoleLinks(rm, op, rules);
> |         }
> |     }
>  @ <...>/node_modules/casbin/lib/esm/model/index.js 16:0-24 16:0-24
>  @ <...>/node_modules/casbin/lib/esm/index.js
>  @ <...>/node_modules/casbin-mongoose-adapter/src/adapter.js
>  @ <...>/node_modules/casbin-rbac/index.js
>  @ <...>/packages/backend/services/rbac/createPolicies.js
```

(this error specifically is b/c the esm version uses conditional chaining, which requires transpiling- that doesn't happen since node_modules is excluded form the .js loader in webpack's config.

So my question - is there some way to specify to webpack to load the cjs version of the module? 

My investigations so far - this works without serverless-bundle (as cjs is automatically picked).
While I can load a submodule like so ``import { newEnforcer } from "casbin/lib/cjs"``, some other external imported packages also load that library and use ``require('casbin")` which also breaks the build process.

Any help is appreciated!

**Comment by hsluoyz** [comment]
@nodece any possible reasons that caused this?

**Comment by nodece** [comment]
@mkherlakian @hsluoyz I made a PR for this: https://github.com/casbin/node-casbin/pull/219.

**Comment by hsluoyz** [comment]
@mkherlakian PR merged: https://github.com/casbin/node-casbin/pull/219

**Comment by mkherlakian** [comment]
Awesome! @nodece @hsluoyz thank you guys!
