### ISSUE TITLE
Option to disable es6 import/export

### ISSUE THREAD

**Issue by sharanrprasad** [AnomalyInnovations/serverless-bundle#18]
Is it possible to provide an option to disable es6 import export?

**Comment by jayair** [comment]
Hmm no there isn't. How come you want to disable them?

**Comment by sharanrprasad** [comment]
It's just that we have used common JS modules for all our node applications and was trying to keep it consistent. No worries. Thanks for the reply.

**Comment by jayair** [comment]
No worries.

**Comment by KeKs0r** [comment]
i know this is not really a concern for this plugin, but I had the same question and thought I might share the use case for it:
I am building my app as a monorepo with multiple services. Some common dependencies are bbuilt with commonjs and consumed by my serverless-services.
Another scenario is the ease of debugging and not requiring transpilation while running simple node scripts. I usually have my business logic in common files that can be triggered from lambda or from cli / debugger which is just slightly more complex if it requires some transpilation.

**Comment by jayair** [comment]
Ah I see, thanks for sharing. So you have cases where you want to skip the transpiling altogether.
