### ISSUE TITLE
Outdated node-sass version

### ISSUE THREAD

**Issue by jaads** [AnomalyInnovations/serverless-bundle#184]
The dependency `node-sass 4.14.1` makes use of `node-gyp 3.8.0` which in turn uses Python 2 under the hood.
Hence `serverless-bundle` relies on Python 2 in the end with the problem being that Python 2 is no longer supported since the beginning of 2020: [https://www.python.org/doc/sunset-python-2/](https://www.python.org/doc/sunset-python-2/)

The newest version of `node-gyp` does not need Python 2 anymore and `node-sass` was recently updated to use this new version of `node-gyp` [node-sass/issues/2716](https://github.com/sass/node-sass/issues/2716), [newest-package.json](https://github.com/sass/node-sass/blob/06f3ab47297fbad5e81244c909afec596d8a1635/package.json#L66)

So please upgrade `node-sass` to  its newest version (5.0.0) so `serverless-bundle` can be used without having Python 2 installed on the machine.

**Comment by jayair** [comment]
Thanks for letting us know! Feel free to open a new PR with this.

**Comment by jaads** [comment]
done #188
