### ISSUE TITLE
 Failed to load config "developit" to extend from. error in serverless-bundle 4.1.0 and 4.2.0 

### ISSUE THREAD

**Issue by s1mrankaur** [AnomalyInnovations/serverless-bundle#198]
When using serverless-bundle, I get  4.1.0 and 4.2.0 

```
Error: Failed to load config "developit" to extend from.
  Referenced from: /home/abc/swagger-typescript-test/node_modules/@babel/preset-modules/package.json
```

I do have the following config where it says developit:

```
  "eslintConfig": {
    "extends": "developit",
    "rules": {
      "no-console": 0,
      "new-cap": 0
    }
  },
```

It works just fine with  "serverless-bundle": "^4.0.1" though. How can this be fixed while using the latest version of serverless-bundle.

**Comment by joewestcott** [comment]
Likely the same issue as https://github.com/AnomalyInnovations/serverless-bundle/issues/175
