### ISSUE TITLE
Optional chaining for JS

### ISSUE THREAD

**Issue by Talg123** [AnomalyInnovations/serverless-bundle#219]
I think its pretty straight forward, the package not support 
new features from JS, such as optional chaining, which is a big deal when developing.
I cant build with the package.

**Comment by michaelwclark** [comment]
I actually added this a while ago, not sure why it's not working. 

https://github.com/AnomalyInnovations/serverless-bundle/pulls?q=is%3Apr+is%3Aclosed+author%3Amichaelwclark
