### ISSUE TITLE
`analyzeBundle` flag

### ISSUE THREAD

**Issue by krishnagopinath** [AnomalyInnovations/serverless-bundle#227]
Thank you for this amazing project! 

I was wondering if there was any interest in adding a `analyzeBundle` flag, backed by the awesome [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) plugin. Here are some use cases:

* This would give us an indication of how large our bundle is.
* What packages we are using and how much memory each package is taking up.
* Answers to questions like: "Did we accidentally include `aws-sdk` in project dependencies?"

Part of me feels like this maybe out of scope of this project, but since we don't have direct access to override the default `webpack.config.js` file, this seems like the best next step. Happy to brainstorm other ideas as well! I'm also happy to make a PR for this if necessary!

**Comment by jayair** [comment]
Thank you!

I think it makes sense to add this as an option. Does this spit out a file can then be analyzed later?

If you could give me a quick sense of how this might be implemented then I can give you some feedback and you can turn that into a PR?

**Comment by krishnagopinath** [comment]
Thanks for the response, @jayair!
 
I had a some ideas as to how this could be done:

### Option 1: Static html file

* Pass in the `analyzeBundle` flag

```
# serverless.yml

custom:
	bundle:
		analyzeBundle:
			path: './some-path/to-drop/html/file'
	
```

* This generates a static html file in the path specified for the built lambdas. In case of a mono repo, this could generate a bunch of html files in the patch specified.

### Option 2: Simply generate stats file that webpack provides.[

Webpack has a way to produce stats via CLI](https://webpack.js.org/api/stats/). The bundle analyzer plugin could be used to generate that file (using the `generateStatsFile` option), which could then be fed into other tools like http://chrisbateman.github.io/webpack-visualizer/

Which one of these would you prefer? I like Option 2 because it is more portable. Stats files are pretty common in the webpack world.

**Comment by jayair** [comment]
Thank you. Yeah option 2 makes more sense. I would prefer if we defaulted the path to something sensible so they don't have to set it, unless they really wanted to. Could we put this into the `.serverless` or `.webpack` (I'm not sure if serverless-webpack still uses this) directory?

**Comment by krishnagopinath** [comment]
It looks like `.serverless` directory gets the zipped bundles. I guess it makes sense to drop these stats in there as well.

**Comment by krishnagopinath** [comment]
@jayair for now, I'll branch off of the `master` branch.

**Comment by jayair** [comment]
The `master` branch works for now. Thanks!

**Comment by krishnagopinath** [comment]
@jayair created https://github.com/AnomalyInnovations/serverless-bundle/pull/242 for this feature.

**Comment by krishnagopinath** [comment]
I will restart work on this, now that we're fully on webpack 5.

**Comment by dror-weiss** [comment]
@jayair, did you get a chance to review #269?
