### ISSUE TITLE
v5.0.0 is in beta

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-bundle#229]
A huge thanks to @thomaschaaf for putting this together. It includes:

- Webpack 5 update
- Esbuild loader option
- eslint-webpack-plugin instead of eslint-loader

Refer to the original PR https://github.com/AnomalyInnovations/serverless-bundle/pull/208.

Please help us test it. We are creating canary releases.

``` bash
$ npm install --save-dev serverless-bundle@canary
```

**Comment by jayair** [comment]
@thomaschaaf we need to update the README. Is the esbuild option the only thing we need to add to it?

**Comment by joewestcott** [comment]
Hi both, I'm receiving this error after upgrading to `5.0.0-beta.0` from `v4.2.3`:

```
Error: Failed to load config "medikoo" to extend from.
Referenced from: ../node_modules/2-thenable/package.json
```

Setting `custom.bundle.disableForkTsChecker` to `true` does resolve the issue though.

**Comment by jayair** [comment]
@joewestcott Is this while bundling TS files?

**Comment by joewestcott** [comment]
> @joewestcott Is this while bundling TS files?

Yes, removing the `tsconfig.json` file also solves it

**Comment by jayair** [comment]
@joewestcott It looks like a fix that we had in https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v4.2.3 has not been merged here. That should resolve this.

@thomaschaaf I ran into a strange issue that I'm hoping you can take a look at. I was trying to merge some changes but when I regenerate the package lockfile for this branch, the Lambda functions aren't being transpiled anymore.

I created a branch to test this and here's a PR to compare the changes https://github.com/AnomalyInnovations/serverless-bundle/pull/230.

Here are the steps to reproduce.

- Delete the package lockfile
- Remove the `node_modules` dir
- Run `npm install`
- Head over to `tests/base` and run `serverless invoke local -f hello`. It should fail with `SyntaxError: Unexpected token 'export'`

Let me know if you are able to reproduce the issue.

**Comment by jayair** [comment]
Just digging into this a bit more, I wonder if it has to do with the version of Serverless Framework. I'm using `2.37.0`. If anybody else can try this out that would be helpful.

**Comment by thomaschaaf** [comment]
Yeah I had to stay at serverless v2.29.0. https://github.com/AnomalyInnovations/serverless-bundle/pull/208/commits/2432f14ef8a98f18e52cfc1debb1d5deca9fc432

**Comment by jayair** [comment]
Yeah I found this as well. It seems like the recent versions of Serverless Framework are completely breaking this? Does anybody want to take a look at whats going on?

**Comment by thomaschaaf** [comment]
I found it: Rename servicePath vars to serviceDir (#9307) (e8c8f1c) (Mariusz Nowak) I will make a new pr.

**Comment by jayair** [comment]
Appreciate it!

**Comment by jayair** [comment]
Is it this https://github.com/AnomalyInnovations/serverless-bundle/blob/master/index.js#L79?

If you are making the change, can you do it in master instead?

**Comment by thomaschaaf** [comment]
2.37.1 brings back the old behavior. So there is actually nothing to be done except not using 2.36.0 or 2.37.0.

**Comment by jayair** [comment]
Thanks for looking into it. Serverless Framework versions aren't very reliable.

**Comment by jayair** [comment]
@joewestcott Pushed `5.0.0-beta.1` with a fix for that issue.

**Comment by joewestcott** [comment]
> @joewestcott Pushed 5.0.0-beta.1 with a fix for that issue.

Lovely! Thanks both for your efforts. Upgrade to `v5.0.0-beta.1` is seemless now and without issues, as far as I can tell.

I did try to enable `custom.bundle.esbuild` though, and got this during build with my handler:

```
ERROR in path/to/handler
Module not found: Error: Can't resolve 'esbuild-loader' in '/node_modules/serverless-bundle/src'
```

Installing `esbuild-loader` in my repo solved the issue, but didn't have an effect on the build time, unfortunately.

**Comment by thomaschaaf** [comment]
I will enable esbuild for minimization (https://github.com/privatenumber/esbuild-loader#js-minification-eg-terser) in my next PR. But for replacing tsc it's not better because webpack is the bottleneck.

**Comment by jayair** [comment]
Merged https://github.com/AnomalyInnovations/serverless-bundle/pull/235

Cut a new release `v5.0.0-beta.2` with it.

**Comment by henhal** [comment]
FWIW: I verified that this solved [issues](https://github.com/serverless-heaven/serverless-webpack/issues/824) I had with private class fields when using serverless-bundle 4.3.1. :+1: :+1:

**Comment by jayair** [comment]
Awesome! Hey all, I'd like to merge this. Anybody run into any issues with this?

**Comment by alertme-edwin** [comment]
Thanks for your work on this @jayair.  It's been a month since you asked if anyone has had issues with it, and apparently `v5.0.0-beta.2` has been getting [60 downloads per week](https://www.npmjs.com/package/serverless-bundle?activeTab=versions), so hopefully that gives some confidence that it is being used.  Is there anything blocking a final `v5.0.0` release now?

**Comment by jayair** [comment]
It's live!

https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v5.0.0
