### ISSUE TITLE
Release 5.1.0 has not been published to npmjs.com

### ISSUE THREAD

**Issue by bernier** [AnomalyInnovations/serverless-bundle#273]
Github mentions that 5.1.0  is available for the past 5 days but I can't install it.

```
npm install --save-dev serverless-bundle@5.1.0                
npm ERR! code ETARGET
npm ERR! notarget No matching version found for serverless-bundle@5.1.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

https://www.npmjs.com/package/serverless-bundle still shows version 5.0.2 as the latest one.

**Comment by jayair** [comment]
Oh good catch. I think something went wrong with the npm release. Just retried it, let me know if you see it.
