### ISSUE TITLE
Can we please add Webpack expirements config to custom config

### ISSUE THREAD

**Issue by amrsmind** [AnomalyInnovations/serverless-bundle#300]
https://webpack.js.org/configuration/experiments/
I want to set topLevelAwait: true

**Comment by jgwheeler** [comment]
Not being able to deploy functions with top level await on Lambda because of this is a major drag.

**Comment by sweepy84** [comment]
Is this happening?

**Comment by galaxy79** [comment]
I'm using a wasm package and it is erroring out with an error to enable experiments.asyncWebAssembly as true. Do you think this can be added to this package ?

```
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.
You need to enable one of the WebAssembly experiments via 'experiments.asyncWebAssembly: true' (based on async modules) or 'experiments.syncWebAssembly: true' (like webpack 4, deprecated).
```

**Comment by jayair** [comment]
Published in https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v5.4.0
