### ISSUE TITLE
Add raw loader to webpack

### ISSUE THREAD

**Issue by gndelia** [AnomalyInnovations/serverless-bundle#33]
I think a cool feature would be to add [raw-loader from webpack](https://github.com/webpack-contrib/raw-loader) to the configuration

the main benefit that it would allow us to import certificates as dependencies, to programatically connect to, let's say, a documentdb instance

```js
import { MongoClient } from "mongodb";
import caBundle from "raw-loader!./path/to/rds-combined-ca-bundle.pem";

let cachedDb = null;

function connectToDatabase() {
    if (cachedDb) {
        return Promise.resolve(cachedDb);
    }

    return MongoClient.connect(
        process.env.MONGODB_URI,
        { ssl: true, sslCA: caBundle }
    ).then(db => {
        cachedDb = db;
        return cachedDb;
    });
}

export const handler = async (event, context) => {
    const db = await connectToDatabase();
    // Do something with it...
};
```

**Comment by jayair** [comment]
I like the idea. I'm curious about the supported file extensions though. It seems like we would need to hardcode them in? Adding the `.pem` makes sense. But is there some way to tell Webpack to use the `raw-loader` specifically for an import?

**Comment by gndelia** [comment]
> But is there some way to tell Webpack to use the `raw-loader` specifically for an import?

I think that by doing `import foo from !raw-loader.path-to-foo` it forces webpack to use raw-loader if no configuration is specified (Meaning, just the loader installed) 

According to [docs](https://webpack.js.org/loaders/) by using `!<loader-name>` you force to use that specific loader (without any specific configuration). So we could just have the loaders installed, without any extra conf, and then the user would specify a loader.

Maybe we  could provide an option "loaders" where we list which loaders to include (From a set picked by this plugin?) so we don't install all of them - reducing final bundle size

**Comment by jayair** [comment]
Ah I see. Yeah this seems pretty straightforward. Let's start by supporting the `raw-loader`. I can have a look at it soon. Or if you want to take a stab at it, feel free to open a PR.

**Comment by gndelia** [comment]
I think I can create a PR add it during the week

**Comment by jayair** [comment]
@gndelia Great! Yeah it would be good to do this.

**Comment by braco** [comment]
There's still no way to raw-load a file, is that right?

**Comment by jayair** [comment]
I think so. If somebody wants to take this on and add a PR, we can add it in.

**Comment by carlcheel** [comment]
Hey @jayair would you mind taking a look to see if this PR can be included? 

For anyone that comes across this, as a workaround you can install `raw-loader` in your project and use the `import foo from !raw-loader.path-to-foo` webpack syntax. The problem with this approach is that the code is now using a webpack specific syntax, and you have to maintain the version of `raw-loader` but that might not bother you.

**Comment by jayair** [comment]
Awesome. Thanks for taking this on. Looking at your PR now.

https://github.com/AnomalyInnovations/serverless-bundle/pull/106

**Comment by jayair** [comment]
Added here: https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.9.0

Closing.
