### ISSUE TITLE
How can I use the watch option with jest?

### ISSUE THREAD

**Issue by damien-monni** [AnomalyInnovations/serverless-bundle#34]
I am executing my tests using `npm test`:

```
"scripts": {
    "test": "serverless-bundle test"
  },
```

Is it possible to launch jest in watch mode?

Thanks!

**Comment by jayair** [comment]
Have you tried setting the watch mode in the `test` script in the `package.json`? I haven't tested it but I think it should work?

**Comment by damien-monni** [comment]
Yes but I haven't found the right syntax I guess, it didn't work.

**Comment by jayair** [comment]
Hmm I've noticed one of our other users using something like this: https://github.com/AnomalyInnovations/serverless-bundle/issues/4

`serverless-bundle test --watchAll --runInBand`

Does that work for you?

**Comment by damien-monni** [comment]
--watchAll is working, but it doesn't with --watch only. I'm not at my
computer now so I can't tell you the exact error message though.

**Comment by damien-monni** [comment]
It's now working with:

```
"scripts": {
    "test": "serverless-bundle test --watch --runInBand"
  },
```

Thanks!
