### ISSUE TITLE
Webpack still being used for bundling despite ESBuild = true

### ISSUE THREAD

**Issue by james-cohen** [AnomalyInnovations/serverless-bundle#350]
We have set our configuration to use esbuild as per the setup guide:
```
custom:
  config: ${file(./config/config.js)}
  appSync: ${file(${self:custom.config.appsync})}
  lambdaInsights:
    defaultLambdaInsights: true #enables Lambda Insights for all functions
  bundle:
    linting: false
    esbuild: true <--
    sourcemaps: false
    forceExclude:
      - pdfkit
```

However when running deploy, Webpack is still being used:
```
npx serverless deploy -s clinics2-dev
                                                   
Deploying anima-service to stage clinics2-dev (eu-west-2)
AppSync Plugin: GraphQl schema valid
Warning: WarmUp: Skipping warmer "officeHoursWarmer" creation. No functions to warm up.
Warning: WarmUp: Skipping warmer "outOfOfficeHoursWarmer" creation. No functions to warm up.
Bundling with Webpack...
```

I can't find any documentation that specifies additional setup for esbuild other than 'esbuild: true', and there doesn't seem to be a similar issue submitted. Could you please advise if any other configuration is required.

Thank you

**Comment by ShantanuNair** [comment]
@james-cohen Did you figure this out? I'm unsure if this is expected behavior or not

**Comment by james-cohen** [comment]
Unfortunately not, still having the same issue

**Comment by damien-monni** [comment]
Same issue here

**Comment by james-cohen** [comment]
I eventually just migrated over to [serverless-esbuild](https://github.com/floydspace/serverless-esbuild) instead

**Comment by damien-monni** [comment]
@james-cohen I would keep the issue opened as it is not fixed yet.
