### ISSUE TITLE
Failed to load plugin vue: Cannot find module 'eslint-plugin-vue'

### ISSUE THREAD

**Issue by lsbyerley** [AnomalyInnovations/serverless-bundle#38]
I've been looking around for a bundler for my serverless functions and wanted to give this one a try. After downloading, adding it to the plugins list, and running `sls offline start` I get an odd error about the vue eslint plugin.

    ERROR in /handler.js
    Module build failed (from /node_modules/eslint-loader/index.js):
    Error: Failed to load plugin vue: Cannot find module 'eslint-plugin-vue'

I'm not using any Vue files anywhere in this directory, so I'm not sure why it would even be including the vue plugin?

**Comment by jayair** [comment]
@lsbyerley This looks like it is trying to pick up some listing config. Do you have a ESLint config file in your project?

**Comment by lsbyerley** [comment]
Oddly enough, no there isn't an eslint config file in my directory. I'm not sure what could be causing this. I'm just going to close this as I've gone a different route, thanks for the input though
