### ISSUE TITLE
Jest + Dotenv - Doesn't load env variables using "setupFilesAfterEnv" (ignored?)

### ISSUE THREAD

**Issue by Vadorequest** [AnomalyInnovations/serverless-bundle#4]
It looks like setupFilesAfterEnv in package.json is either ignored or misconfigured [doc](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array)

```js
  "jest": {
    "setupFilesAfterEnv": [
      "./jest-preload-env.js",
      "jest-extended"
    ],
    "verbose": true
  },
```

My file `./jest-preload-env.js` contains the following:
```js
require('dotenv').config({ path: '.serverless/.env' });

if (process.env.NODE_ENV !== 'test') {
  throw Error('Non-test environment');
}

```

But adding console.log there doesn't seem to be executed.
This breaks my tests, as ENV variables aren't loaded before tests are executed.

I'm running `serverless-bundle test --watchAll --runInBand`, which seems to call jest (through , but after looking at the source, I believe the `setupFilesAfterEnv` is ignored by the plugin.

**Comment by Vadorequest** [comment]
I've created a sample that reproduce this issue at https://github.com/UnlyEd/boilerplates-generator/pull/9

I basically copied an existing template with serverless and applied serverless-bundle, see `FIXME` comments. Tests are passing.

**Comment by jayair** [comment]
I think we might not be passing those in. I'll need to investigate this.

**Comment by jayair** [comment]
I looked at what Create React App does for this and added support to override some Jest options.

https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.2.3

**Comment by Vadorequest** [comment]
Interesting, I'm gonna give it a try!

I tried running my test, and got:
```
Out of the box, serverless-bundle only supports overriding these Jest options:

  • collectCoverageFrom
  • coverageReporters
  • coverageThreshold
  • extraGlobals
  • globalSetup
  • globalTeardown
  • resetMocks
  • resetModules
  • setupFilesAfterEnv
  • snapshotSerializers
  • transform
  • transformIgnorePatterns
  • watchPathIgnorePatterns.

These options in your package.json Jest configuration are not currently supported by serverless-bundle:

  • verbose

If you wish to override other Jest options, consider using serverless-webpack directly instead.

error Command failed with exit code 1.

```

**Comment by Vadorequest** [comment]
`setupFilesAfterEnv` works fine and fixed my tests! 💯

**Comment by Vadorequest** [comment]
The verbose option could be supported in a future version, meanwhile I believe we can close this issue ;)

**Comment by luckyyang** [comment]
jest.config.js
```
module.exports = {
  setupFilesAfterEnv: ['./jest.setup.js'],
}
```

jest.setup.js
```
require('dotenv').config({
  path: './.env',
});
```

.env
```
RPC_ENDPOINT=http://xxx.xxx.xxx.xxx
MODE=DEV
```
