### ISSUE TITLE
Testing 1.3.0-beta.4

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-bundle#47]
Hi all,

We've got a new beta that we could use some help testing before releasing out publicly. It resolves the following issues:

- Automatically load `.env` for the tests @Steffan-Carlos  (https://github.com/AnomalyInnovations/serverless-nodejs-starter/issues/51)
- Adding support for ignoring packages.
  - @aychtang Can you try it with the `pg` package (https://github.com/AnomalyInnovations/serverless-bundle/tree/beta#pg)
  - @compwright Can you try it for `redis` (https://github.com/AnomalyInnovations/serverless-bundle/tree/beta#redis)
- Using the provider runtime to figure out the target Node version @JakeChampion (https://github.com/AnomalyInnovations/serverless-bundle/pull/41)

You can install the new beta using:

``` bash
$ npm install --save-dev serverless-bundle@1.3.0-beta.4
```

Give it a try and let me know how it goes.

Thank you!

**Comment by clementAC** [comment]
webpack is unable to find my global package.json when I'm a a "micros service directory" to deploy. Serverless bundle is looking on the local directory.

**Comment by jayair** [comment]
@clementAC Can you open a separate issue for this with your project structure?

**Comment by jayair** [comment]
We published the new update!

https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.3.0
