### ISSUE TITLE
Babbel and sequelize - Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by r3m4k3** [AnomalyInnovations/serverless-bundle#48]
Hi there,

I'm trying to use this plugin with lambda, sequelize and postgres.
But unfortunately I cannot have it working, I get this error: Cannot assign to read only property 'exports' of object '#<Object>'.
I know it's about mixing import and require, however I don't use import statements in my code at all.
The error comes from this file (config.js) - it's really simple:

`module.exports = {
    production: {
        url: process.env.DATABASE_URL,
        dialect: 'postgres',
    },
};`

What can I do with this error? 
Because as I have understood, there's no possibility to change babel settings. 

Best regards

**Comment by danielo515** [comment]
Try changing module.exports by export default or even better, export each property separately

**Comment by knvpk** [comment]
@r3m4k3  , did the @danielo515 suggestion worked?
In my project there are several places need to change, any other alternative @danielo515 ?

**Comment by knvpk** [comment]
Is this plugin will help https://babeljs.io/docs/en/babel-plugin-proposal-export-default-from?

**Comment by r3m4k3** [comment]
@knvpk I have rewritten my code to use export default.
Haven't tried the plugin you've mentioned.
