### ISSUE TITLE
How can I analyze the generated bundle?

### ISSUE THREAD

**Issue by s14k51** [AnomalyInnovations/serverless-bundle#56]
Hi, I really love using serverless-bundle. 

I'm wondering if there is a way to analyze the generated bundles to check what code is going into them, with something like webpack-bundle-analyzer or such sort. Is it possible with the serverless-bundle plugin? 

Thank you.

**Comment by jayair** [comment]
We don't have a built-in way to do this currently. I had done this in the past by manually editing the `webpack.config.js` that is included.

**Comment by s14k51** [comment]
@jayair Ok, thank you for the information.
