### ISSUE TITLE
Add support for graphql loaders?

### ISSUE THREAD

**Issue by rad182** [AnomalyInnovations/serverless-bundle#58]
Hello is there a way to add loader to support .graphql files?

**Comment by jayair** [comment]
Hmmm do these files need an additional Webpack loader? I don't think we support this natively. But you can copy files to the bundle. Would that work?

**Comment by rad182** [comment]
yes in my current project i'm using https://github.com/apollographql/graphql-tag
```
{
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader',
      },
```

As for copying. I tried that also but can't wait make it work.
I ended up using js
```
gql`
type Query {
    hello: String
  }
`
```

**Comment by mohamedGamalAbuGalala** [comment]
Check [this link](https://graphql-modules.com/docs/recipes/development-environment#webpack)

this Will guide you to how we need to support graphql loaders.

**Comment by emre-haufe-canei** [comment]
I have just make a PR for supporting gql and graphql files

**Comment by jayair** [comment]
Just leaving this here and closing this thread to avoid future confusions.

https://github.com/AnomalyInnovations/serverless-bundle/pull/65#issuecomment-652524223
