### ISSUE TITLE
Doc - Using custom .babelrc

### ISSUE THREAD

**Issue by Vadorequest** [AnomalyInnovations/serverless-bundle#6]
It's not clearly stated in the doc what should be done when we use a custom .babelrc, that covers more ground than this plugin does.

For instance, given the following `.babelrc` file, which is customised to support some Next.js advanced configuration, what should I keep?

```
{
  "plugins": [
    "source-map-support" // Keep this? Seems like it's covered already
  ],
  "presets": [
    [
      "next/babel", // This is special, should be kept IMHO
      {
        "styled-jsx": {
          "optimizeForSpeed": true,
          "vendorPrefixes": true,
          "sourceMaps": true,
          "plugins": [
            "styled-jsx-plugin-sass"
          ]
        }
      }
    ]
  ]
}

```
---
Also, in the special Next.js case, where they already setup a bunch of things through their `next/babel` preset, should we handle that case in a particular way? See https://github.com/zeit/next.js/#customizing-babel-config

**Comment by jayair** [comment]
Yeah similar to the custom Webpack config idea, we don't have plans to support a custom Babel config just yet. I think serverless-webpack is pretty good if you just want to manage your own.

**Comment by Vadorequest** [comment]
I'm closing this to avoid discussing the same topic on 2 separate issues.

**Comment by Vadorequest** [comment]
See https://github.com/AnomalyInnovations/serverless-bundle/issues/7
