### ISSUE TITLE
TypeScript Support in Beta

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-bundle#61]
First off thanks to @tume @rklubenspies @codinronan for helping.

The new beta branch https://github.com/AnomalyInnovations/serverless-bundle/tree/beta now has TS support. Since I'm not much of a TS user, I could use some help getting this to a public release. Here is how you can help.

Start by using the beta version and reporting issues:

``` bash
npm install --save-dev serverless-bundle@1.4.0-beta.0
```

@rklubenspies let's look at supporting a TS single config file as you mentioned here - https://github.com/AnomalyInnovations/serverless-bundle/pull/51#issuecomment-582086181. Do most people use a single config file? If so, then we should build it into the plugin right?

**Comment by tume** [comment]
Great to see this progressing. Thank you all.

One thing that might be missing is testing the code with jest. Seems that you need to have `@babel/preset-typescript` enabled for jest to strip the type annotations or use https://github.com/kulshekhar/ts-jest for type checking also.

**Comment by jayair** [comment]
I see. Is anybody willing to take a crack at this?

Also, we might have to look at the ESLint config for TS I'm guessing?

**Comment by tume** [comment]
It would be nice to hear how people are normally testing ts apps and what are the best practices? I can configure once there is a clear direction where to go. I will experiment myself but might take a while until I have a complete setup. 

Also noticed that you can extend other configs from tsconfig.json which means you could have one tsconfig.json at root-level and just reference that from service level. Still needs to have the tsconfig.json in every service but at least can have all the common config in one file.

**Comment by RatulSaha** [comment]
It would be ideal to not have to add tsconfig for each service. The suggestion at https://github.com/AnomalyInnovations/serverless-bundle/pull/51#issuecomment-582086181 seems useful, although should we do that manually in node_modules or something?

**Comment by RatulSaha** [comment]
Also, I am getting a `Error: Cannot find module 'typescript'` at `fork-ts-checker-webpack-plugin/lib/index.js` when compiling. I am guessing I need to add typescript to my project explicitly, but not sure how. I am following the serverless-monorepo style, added tsconfig.json to each service.

**Comment by tume** [comment]
@RatulSaha Yeah you need to install typescript yourself to your service.

One config for root-level might be a good idea to support but still think that supporting separate tsconfig.json in each service is a valid thing as well, might need to have a bit different config based on the service. We are now e.g. migrating from pure js to ts and when mixing both makes sense that the compiler is not so strict and when everything is in Ts we can have it stricter by default.

**Comment by tume** [comment]
Created PR for basic test setup with ts-jest: https://github.com/AnomalyInnovations/serverless-bundle/pull/67

**Comment by avin-kavish** [comment]
Thanks for doing this. One thing I noticed it launches seperate typeschecking instances for each entry point at once when  `package: individually: true` is set. I only have 8 functions at the moment so it's fine but I expect to have more. I'm not sure if this is the best way to type check. One typecheck across the whole codebase should be enough. Entry points don't make a difference in the context of typechecking.

**Comment by avin-kavish** [comment]
Also, does tree shaking work for `node_modules` ? If not invidual packages might not be worth it.

**Comment by karl-run** [comment]
Not sure if I messed up, but for me it did not work importing modules from within an imported module, then the module would just be an empty module.

```
handler.ts
  -> myOtherFile.ts (works)
    -> myUtils.ts
```

In this scenario `myOtherFile.ts` importing `myUtils.ts` would just get an empty module. However myUtils.ts is still loaded, because `console.log` on the root of myUtils.ts would still show up in the output.

This was observed together with `serverless-offline`.

**Comment by david-l-riley** [comment]
So far, this is mostly working for me. However, there are a few things that would be nice to be able to override in the Webpack config, but we're explicitly prevented from doing so for some reason? For example, if I need to add aliasing for things that need overrides because they're not compatible out of the box with Webpack, I can't do that.

**Comment by jayair** [comment]
Published a new beta with https://github.com/AnomalyInnovations/serverless-bundle/pull/67

```
$ npm install --save-dev serverless-bundle@1.4.0-beta.1
```

**Comment by jayair** [comment]
Pushed another version with https://github.com/AnomalyInnovations/serverless-bundle/pull/65

Supporting `.gql`

``` bash
$ npm install --save-dev serverless-bundle@1.4.0-beta.2
```

**Comment by karl-run** [comment]
Ref. my comment above, I created a minimal reproduction of my issue:

https://github.com/karl-run/serverless-bundle-ts-repro

`handler.ts` imports `other.ts`, this works fine.
`other.ts` imports `third.ts`, this doesn't work. The import from `third.ts` resolves to `{}` for some reason.

**Comment by tume** [comment]
@karl-run managed to get it running with this tsconfig.json 

```
{
  "compilerOptions": {
    "module": "ES6",
    "target": "es2017",
    "rootDir": "./src",
    "outDir": "./dist",
    "noImplicitAny": false,
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "declaration": false,
    "listFiles": false
  }
}
```

Changed target to es2017 and module to ES6. Currently will go through babel after compiling to javascript so can target newer than ES5... didn't dig through (yet) how the produced code is different. Maybe someone who knows ts & Webpack & babel better could explain? :).

**Comment by karl-run** [comment]
Hmm.. Using that `tsconfig.json` I still get the same error.

```
Serverless: GET /test-repro (λ: poll-fields)
Helloooooo
Serverless: Failure: other_1.printValue is not a function
TypeError: other_1.printValue is not a function
```

Could it maybe be related to #29?

**Comment by tume** [comment]
That is strange... I now tried reverting the config to original and mine works still :) 

So deployed the function to AWS and seems to be working with a small amount of testing. Dunno if there is some caching issue with serverless-offline/nodeJS ?  Can now also replicate by removing node_modules and reinstalling them... no idea why that affects anything tough. 

I only managed to do some quick testing but can look a bit more next week if no one else has any better ideas about what is happening before that.

**Comment by avin-kavish** [comment]
What about the multiple typechecking issue?

**Comment by jayair** [comment]
Just pushed another beta. Merged https://github.com/AnomalyInnovations/serverless-bundle/pull/74.

``` bash
$ npm install --save-dev serverless-bundle@1.4.0-beta.3
```

**Comment by thibaultdalban** [comment]
Hi,

When I try to package my service, I hit this error:
```
$ SLS_DEBUG=* serverless package
...
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Starting type checking service...
Serverless: Invoke webpack:package
 
  Syntax Error -------------------------------------------
 
  SyntaxError: Unexpected end of JSON input
  SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at /home/thibault/auditor/node_modules/serverless-webpack/lib/packagers/npm.js:61:47
      at tryCatcher (/home/thibault/auditor/node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.attempt.Promise.try (/home/thibault/auditor/node_modules/bluebird/js/release/method.js:39:29)
      at /home/thibault/auditor/node_modules/serverless-webpack/lib/packagers/npm.js:61:35
      at tryCatcher (/home/thibault/auditor/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/thibault/auditor/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/thibault/auditor/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/thibault/auditor/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/thibault/auditor/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/thibault/auditor/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/thibault/auditor/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/thibault/auditor/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/thibault/auditor/node_modules/bluebird/js/release/async.js:15:14)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at ServerlessPlugin.<anonymous> (/home/thibault/auditor/node_modules/serverless-webpack/index.js:102:51)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.1
     Framework Version:         1.67.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

I successfully packaged my service using `serverless-webpack` but I don't understand why it fails using `serverless-bundle`.
Do you have any clues?

**Comment by jayair** [comment]
Minor update with https://github.com/AnomalyInnovations/serverless-bundle/pull/79

``` bash
$ npm install --save-dev serverless-bundle@1.4.0-beta.4
```

**Comment by Maxim-Filimonov** [comment]
> What about the multiple typechecking issue? Did anyone run into that?
I'm running into type checking issues with top level package.json dependencies. 
```
ERROR in /src/functions/node_modules/graphql-request/dist/src/index.d.ts(11,18):
TS2304: Cannot find name 'Headers'.
ERROR in /src/functions/node_modules/graphql-request/dist/src/index.d.ts(22,14):

Headers in defined in `types.d.ts`.
```

The function runs without issues it's just type checker unhappy about something.

**Comment by Maxim-Filimonov** [comment]
It seems it doesn't recompile with `sls offline`. 

At least when I changed handler.ts and then manually run requests via curl it returned to me old response.

**Comment by david-l-riley** [comment]
I've noticed this as well (including with older versions), though I keep forgetting to mention it. `sls offline` (including the 6.0 beta) will recompile it, which does at least give any linting/syntax errors, but it doesn't seem to reload the Webpacked content.

**Comment by groffcole** [comment]
I'd like to try using `serverless-bundle` with TypeScript support but I'm not exactly sure how to start. For a regular project, I'd create a new Serverless Framework project using the AWS Node.js template, install `serverless-bundle`, update the `serverless.yml` file to include the plugin, and then things just work.

What extra steps do I need to do so that I can do the steps above but write my code using TypeScript?

**Comment by patrykkrawczyk** [comment]
Because of the added dependency `concat-text-webpack-plugin` the beta version does not work with LTS version of Node (12+).
I've created an issue within their repository to update it https://github.com/namics/webpack-concat-text-plugin/issues/6

**Comment by patrykkrawczyk** [comment]
The mentioned issue is closed and we are supposed to use version 0.1.6 to mitigate mentioned error with `concat-text-webpack-plugin`

**Comment by jayair** [comment]
@patrykkrawczyk If we are using the older version, can you submit a PR to the beta branch?

@groffcole I'm not terribly familiar with TS but can you post the issues you ran into and the folks here could help.

**Comment by jayair** [comment]
Adding TS support for ESLint. Thanks to https://github.com/AnomalyInnovations/serverless-bundle/pull/85.

``` bash
$ npm install --save-dev serverless-bundle@1.4.0-beta.5
```

**Comment by patrykkrawczyk** [comment]
@jayair added the change https://github.com/AnomalyInnovations/serverless-bundle/pull/89
Can we also rebase beta branch to include fix for formidable?

**Comment by jayair** [comment]
Yup merged https://github.com/AnomalyInnovations/serverless-bundle/pull/89 and up to date with master.

``` bash
$ npm install --save-dev serverless-bundle@1.4.0-beta.6
```

**Comment by roni-frantchi** [comment]
Hey.  
Just wanted to bring something up - 

One feature of TypeScript that is very useful in monorepos is TypeScript's [Path Mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html) so that one may `import` based on relative base url set in `tsconfig`.  
WebPack doesn't support those kinds of import natively, and thus we're using [this plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin) to do that.  

I'm not sure how we'd be able to use this bundler instead and still cope with TypeScript's path mappings.

**Comment by klardotsh** [comment]
@roni-frantchi it needs cleaned up a bit (the changes/fixes I did were very bespoke to our use at Logixboard, barely documented, etc.) but check out https://github.com/logixboard/serverless-bundle/commits/lxb, and specifically https://github.com/logixboard/serverless-bundle/commit/3739db912982adebeffdd752a07e02bf9b6498af, which uses https://github.com/dividab/tsconfig-paths-webpack-plugin to solve that problem (in exactly the same context - monorepo with TS path aliases)

**Comment by dhavalocked** [comment]
> Hmm.. Using that `tsconfig.json` I still get the same error.
> 
> ```
> Serverless: GET /test-repro (λ: poll-fields)
> Helloooooo
> Serverless: Failure: other_1.printValue is not a function
> TypeError: other_1.printValue is not a function
> ```

You found any solution to this? I am facing similar problem.

**Comment by StErMi** [comment]
is there some example that shows off how you should correctly structure your code with the typescript version fo the plugin? Maybe a TS version of the [serverless-nodejs-starter](https://github.com/AnomalyInnovations/serverless-nodejs-starter) and [serverless-stack-demo-api](https://github.com/AnomalyInnovations/serverless-stack-demo-api)

**Comment by dhavalocked** [comment]
Typescript support is not yet available in master.  You can install using [this](https://github.com/AnomalyInnovations/serverless-bundle/issues/61#issuecomment-613087586).

[#51-comment](https://github.com/AnomalyInnovations/serverless-bundle/pull/51#issuecomment-582086181) show details on how to use it with typescript.

I am working on this since last 2 weeks and its amazing, let me know if you need a serverless monorepo starter.

**Comment by StErMi** [comment]
@dhavalocked a serverless monorepo starter would be amazing, it would allow me to learn (I'm totally new to AWS/serverless) from a working example that follows the best practice.

**Comment by dhavalocked** [comment]
@StErMi I have created a sample [repo](https://github.com/dhavalocked/typescript-serverless-monorepo).. This should get you started. Make sure you are using `serverless-bundle beta release`.

There are ways to optimise many things in this repo However this is just a basic structure that can get you started.

**Comment by jayair** [comment]
Merging latest changes in master (https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/1.5.0 & https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/1.6.0) and bumping up the version.

``` bash
$ npm install --save-dev serverless-bundle@2.0.0-beta.0
```

I think we should start preparing for a public release of v2 with TS support. It would be good to figure out what else we need to fix/support!

**Comment by StErMi** [comment]
@jayair I'm not a super TS expert in the config/building but I'm happy to give you support in testing. I think that an optimized config could bring a lot of benefits but I really don't know how to help here :D

**Comment by janjanarnaldo** [comment]
Hi guys, do you have any idea how to isolate the tsconfig on a backend for frontend structure? Basically, this typechecks the entire repo instead of the serverless folder only. Here's my sample structure:

├── client # Frontend components
├── serverless
│   └── src #handlers
├── services
│   └── application
│   │   └── functions.yml
│   │   └── serverless.yaml # per service config
└── serverless.yml # root serverless config
└── tsconfig.json

Running serverless offline start will typecheck the client folder, but we only want to check the serverless folder. How do we do that? I'm thinking of creating a separate tsconfig.server.json and exclude the client folder for bff but I'm unsure how to make serverless-bundle target that particular config file. Would appreciate hearing your thoughts.

**Comment by StErMi** [comment]
Hi, @jayair I have a question. I've some config.ts files that are not directly required by the code but a library is trying to find them. It's a problem because webpack is not including them in the build.

Is there a way to configure serverless-bundle to include them?

**Comment by jayair** [comment]
@janjanarnaldo That's interesting. Is the issue only with the offline plugin? Or is there an issue with serverless-bundle as well?

@StErMi Maybe create a new issue with a sample project and some steps to reproduce?

**Comment by StErMi** [comment]
@jayair I've created another issue here: https://github.com/AnomalyInnovations/serverless-bundle/issues/102 I know that's pretty specific but it would be really cool because there are a lot of users out there that develop Alexa skills and I think this will improve the dev ecosystem by a lot!

**Comment by janjanarnaldo** [comment]
Hi @jayair I think it's only for the bundle. Maybe we should expose a custom bundle variable to typecheck/lint specific folders only, if left undefined would typecheck/lint the root folder. I'm already using this beta in my project but I turned off linting in the custom settings because I couldn't see a fix on my issue. Thanks!

**Comment by jayair** [comment]
An update, I'm working towards getting TS support to a public release.

Merging with master and adding support for TypeScript's path mapping. Thanks @roni-frantchi @klardotsh.

Upgrade with:

``` bash
$ npm install --save-dev serverless-bundle@2.0.0-beta.1
```

@dhavalocked Can you try this minimal `tsconfig.json`:

``` json
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node"
  }
}
```

@janjanarnaldo I'll have to look at this next.

**Comment by jayair** [comment]
Just added support for specifying custom tsconfig path.

``` yml
custom:
  bundle:
    tsConfig: 'tsconfig.special.json'
```

Upgrade with:

``` bash
$ npm install --save-dev serverless-bundle@2.0.0-beta.2
```

@janjanarnaldo This should fix your issue.

I think we are ready to push TS support to master and release it publicly. Does anybody want to give the new beta a test and give it a thumbs up?

**Comment by jayair** [comment]
It's alive! Thank you all for making this happen.

https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v2.0.0

Update using:

``` bash
$ npm install --save-dev --save-exact serverless-bundle@2.0.0
```

**Comment by janjanarnaldo** [comment]
**exciiiitteeeeed**
