### ISSUE TITLE
Problem with custom request authorizer

### ISSUE THREAD

**Issue by caligo-erik** [AnomalyInnovations/serverless-bundle#68]
I have a problem with the custom request authorizer not working with the default setup.

Reproduction steps: take this boilerplate project where I added a dummy custom request authorizer
[serverless-boilerplate.zip](https://github.com/AnomalyInnovations/serverless-bundle/files/4203690/serverless-boilerplate.zip)

Deploy it and click on the URL in the console. Alternatively, go to Amazon API Gateway and click on Authorizers and Test. Check the Cloudwatch logs, you will get a "Cannot set property 'handler' of undefined" exception.

Since the "plugin does not support customizing the Babel and Webpack configs", the only workaround is to open the lambda file(s) in the Amazon Console and copy-paste the original code.

Any suggestions would be very helpful.

**Comment by gndelia** [comment]
if you're packaging your functions with serverless-bundle, you need to expose your functions as ES6 modules

in your custom handler you need to expose your function as 

```
export const handler = async (event, context, callback, dataProvider) => {
  console.info(`incoming event ${util.inspect(event, false, null, false)}`);
  callback(null, generatePolicy('user', 'Allow'));
}
```

and import the dependencies with import statements

**Comment by caligo-erik** [comment]
Thanks for your reply.

Since this problem concerned only our custom authorizer function, I came to the wrong conclusion.
After a comparison with other lambda functions I have updated the code as follows:

`
module.exports = {
  handler: async (event, context, callback) => {
    callback(null, generatePolicy('user', 'Allow'));
  }
}
`

Now it works, thanks.
