### ISSUE TITLE
Feature/Question: typescript support?

### ISSUE THREAD

**Issue by aprat84** [AnomalyInnovations/serverless-bundle#8]
Hi everybody.

Would it be possible, in near future, maybe in next minor/major version, to support Typescript? 
Something like an option `typescript: true/false` in serverless.yaml.

This would mean, at least, to install some extra packages (ts-loader, typescript) and tweak webpack.config.js depending on that option.

Thanks!

**Comment by jayair** [comment]
Yeah we've definitely gotten a few requests for TS. I'm personally not super familiar with it. But it would be good if we can even support it without needing a config option.

If anybody wants to try and take this on, I'd be happy the help get them started.

**Comment by Vadorequest** [comment]
I suggest you add a tag `help-wanted` then ;)

Here is our latest newborn project using TS, I guess it can be used for inspiration:
https://github.com/UnlyEd/conditions-matcher

What's important to know is that you use the `tsc` binary to compile from TS to ES5. By convention we use the `src` folder for sources, and `lib` folder for build, the lib folder is what's released on NPM (ES5 compatible).

- https://github.com/UnlyEd/conditions-matcher/blob/master/package.json
- https://github.com/UnlyEd/conditions-matcher/blob/master/tsconfig.json

**Comment by gndelia** [comment]
this feature would be great. I would like to take a look, but I think I might have some time in the incoming weeks, not right now. So if anyone else is available, that would be great. Otherwise, maybe in november/december I might start taking a look (it would be useful for a project I am working with which uses this library)

**Comment by Cryoware** [comment]
Have you tried placing `serverless-plugin-typescript` above all plugins?
```
plugins:
  - serverless-plugin-typescript
  - serverless-bundle
```

**Comment by cinqi** [comment]
I tried to use serverless-bundle with serverless-plugin-typescript, it does not work, at leat out of the box. End result is two versions of handler files, one compiled by typescript and one by webpack (.build/handler.js and ./build/.webpack/handler.js)

**Comment by jayair** [comment]
We have this in beta now. Opened a new issue to track progress https://github.com/AnomalyInnovations/serverless-bundle/issues/61.
