### ISSUE TITLE
ignorePackages custom option is not working as expected.

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [AnomalyInnovations/serverless-bundle#83]
I've tried to ignore the chrome-aws-lambda package but it's not ignored as expected. Please check the following code and correct me if I'm wrong.

custom:
  bundle:
    ignorePackages:
      - chrome-aws-lambda

**Comment by jayair** [comment]
Hi there, I noticed the PR that you opened. Was it related to this issue?

**Comment by BhuvaneshwaranR** [comment]
@jayair  Yes
