### ISSUE TITLE
Problem with aws-sdk in third-party package

### ISSUE THREAD

**Issue by bart** [AnomalyInnovations/serverless-bundle#88]
Hey everyone,

I'm on the latest version of serverless-bundler plugin. When I deploy a service I'm getting the following error when trying to execute lambda function online:

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/blog.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'",
    "Require stack:",
    "- /var/task/blog.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1158:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)",
    "    at Module.load (internal/modules/cjs/loader.js:1002:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:901:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
    "    at internal/main/run_main_module.js:18:47"
  ]
}
```

My blog service uses the `serverless-dynamodb-client` package to fetch data from dynamodb. Looks like this package needs `aws-sdk`. As far as I know it should be installed on AWS Lambda already so I don't understand why I'm getting this error. Any idea what I do wrong or how to solve this issue? It is super annoying. Trying to solve it for more than 6 hours now...

**Comment by bart** [comment]
I created an example project so that you can reproduce in 10 seconds:

https://github.com/bart/serverless-bundle-issue-example

**Comment by bart** [comment]
My used third-party package `serverless-dynamodb-client` requires `aws-sdk` as a dependency which causes the error. Reason is this line in index.js of `serverless-bundle`:

```
forceExclude: ["aws-sdk"],
```

If I replace it by

```
forceExclude: [],
```

`aws-sdk` gets packed as external module but for sure blows up the size of that service. So the main question here is: Why does the dependency `aws-sdk` of `serverless-dynamodb-client` doesn't get loaded from Lambda?

**Comment by bart** [comment]
All right, solved it with a fresh mind! For anyone who comes up with the same issue: Reason was the line `NODE_PATH: "./:/opt/node_modules"` set as provider.environment. You must remove this line and it works! You just need it fror serverless projects running on layers which I don't have anymore after splitting up my code into separate services. Cheers!

**Comment by yspreen** [comment]
```
forceExclude: []
```

doesn't actually work for me, see https://github.com/fusebit/everynode/issues/3
