### ISSUE TITLE
Adding permissions support 

### ISSUE THREAD

**Issue by suryacaprice** [AnomalyInnovations/serverless-bundle#92]
Hi can you please add https://www.npmjs.com/package/webpack-permissions-plugin to have the fs support as well in the configuration. We use lots of files in the project and need it for the build to work.

**Comment by suryacaprice** [comment]
Basically i need these options https://nmajor.com/posts/serverless-framework-executable-binaries-aws-lambda

**Comment by jayair** [comment]
We currently support the copy files option. It seems like if we can also copy the files with the right permissions it would address this. I don't think we need a separate option for this. If somebody wants to take this on, here is the relevant part.

https://github.com/AnomalyInnovations/serverless-bundle/blob/36afd2b25cbf78c8c795f2c4a81c5c3cd40e792e/src/webpack.config.js#L106

**Comment by ianpogi5** [comment]
Hi @jayair can you have a look at my pull request?

**Comment by jayair** [comment]
@ianpogi5 Thanks! Taking a look.
