### ISSUE TITLE
error using momonet.js

### ISSUE THREAD

**Issue by wamir79** [AnomalyInnovations/serverless-bundle#94]
how can I add moment.js locale file to serverless bundle? 

Thanks for any help :)

I tried the following:

```
git clone git@github.com:AnomalyInnovations/serverless-nodejs-starter.git
cd serverless-nodejs-starter
npm i moment
```
then in file handler.js add 
```
import moment from "moment";
```
and update hello with just call to `moment();` (to avoid lint error)

when running local run:
```
serverless invoke local --function hello  
```

the error received:
`Error: Cannot find module './locale'`

**Comment by jayair** [comment]
I know what's causing this:

https://github.com/AnomalyInnovations/serverless-bundle/blob/36afd2b25cbf78c8c795f2c4a81c5c3cd40e792e/src/webpack.config.js#L119

It's being done to keep the bundle size small — https://github.com/jmblog/how-to-optimize-momentjs-with-webpack#using-ignoreplugin

Can you try adding the specific locale and let me know if that fixes it?

``` js
import 'moment/locale/fr';
```

**Comment by wamir79** [comment]
Thanks for your help!!

well it didn't solve my issue. i tried other things like copy the file with:

```
custom:
  bundle:
    copyFiles:
      - from: "./node_modules/moment/locale"
        to: "./locale"
```

I put a fork with the tries in:
```
https://github.com/wamir79/serverless-nodejs-starter
```

Thanks again!

**Comment by wamir79** [comment]
issue solved here:

https://stackoverflow.com/questions/61567780/error-using-moment-js-with-serverless-bundle

**Comment by jayair** [comment]
Oh glad that fixed it.
